stdout: {}
stderr: "[vuln] Vulnerability scanning is enabled\n2025-06-10T07:08:52Z\tINFO\t[secret] Secret scanning is enabled\n2025-06-10T07:08:52Z\tINFO\t[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning\n2025-06-10T07:08:52Z\tINFO\t[secret]"
exitcode: 1
cmd: docker run --pull always --rm -v trivy-db:/root/.cache/trivy aquasec/trivy -f json --skip-dirs /home/.openvscode-server/** image nmaguiar/hvscs:latest
