ojob.io/sec/genSecBadge: ''
image: nmaguiar/hvscs:build-lite
file: .github/sec-build-lite.svg
reportFile: .github/sec-build-lite.yaml
scanOptions: '--skip-dirs /home/.openvscode-server/**'
init: {}
msg: Producing a summary of the results...
__key: report
level: info
options: {}
__format: pm
