ojob.io/sec/genSecBadge: ''
image: nmaguiar/hvscs:latest
file: .github/sec-latest.svg
reportFile: .github/sec-latest.yaml
scanOptions: '--skip-dirs /home/.openvscode-server/**'
init: {}
msg: Producing a summary of the results...
__key: report
level: info
options: {}
__format: pm
