name: Docker Image Lite CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
    - '.github/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - '.github/**'
  schedule:
    - cron: '48 0 * * 6'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      name: Build and push
      with:
        platforms: linux/amd64,linux/arm64
        context: "{{defaultContext}}:build"
        push: true
        tags: nmaguiar/hvscs:build-lite
        file: Dockerfile.lite
